# Generated by Django 5.2.1 on 2025-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_vguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
