# Generated by Django 5.2.1 on 2025-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_postvguser_image_alter_vguser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vguser',
            name='avatar',
            field=models.ImageField(blank=True, default='none_avatar.png', null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
