# Generated by Django 5.2.1 on 2025-05-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
