# Generated by Django 5.2.1 on 2025-05-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_chat_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(default=312, max_length=20),
            preserve_default=False,
        ),
    ]
