# Generated by Django 5.2.1 on 2025-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_chat_chat_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('chat_id', 'user1', 'user2')},
        ),
    ]
