# Generated by Django 5.2.1 on 2025-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_postvguser_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvguser',
            name='image',
            field=models.ImageField(upload_to='content', verbose_name='Фото'),
        ),
    ]
