# Generated by Django 5.2.1 on 2025-05-27 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_like_created_at_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
