# Generated by Django 5.2.1 on 2025-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_comment_options_comment_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='postvguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='content', verbose_name='Фото'),
        ),
    ]
